tasks/urls.py
from django.urls import path
from . import views

app_name = "todolist"

urlpatterns = [
    path("", views.index, name="index"),
    path("addtask/", views.add, name="addTask")
]

to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todolist/", include("tasks.urls"))
]

tasks/models.py
from django.db import models

# Create your models here.

tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    # priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

# Create your views here.

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(
        request, "tasks/index.html", {
            "tasks": request.session["tasks"]
        }
    )

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("todolist:index"))
        else:
            return render(
                request, "task/add.html",{
                    "form": form
                }
            )
    return render(
        request, "tasks/add.html", {
            "form": NewTaskForm()
        }
    )

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Add Task</h1>
<form action="{% url 'todolist:addTask' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
<a href="{% url 'todolist:index' %}">View Tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Tasks</h1>
<ul>
    {% for task in tasks %}
        <li>{{ task }}</li>
    {% empty %}
        <li>No tasks for today :)</li>
    {% endfor %}
</ul>
<a href="{% url 'todolist:addTask' %}">Add a new task.</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do List</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>